version: '{build}'
image: Visual Studio 2017
environment:
  nuget_key:
    secure: oguZl00lM10ZBNInx/yyEdx3XqTJrLo4nllAiP8B2xW1MuwRuwcoYG95+lMTMjtV
build_script:
  - ps: ./build.ps1
skip_non_tags: true
test: 'off'
deploy_script:
  - ps: ./build.ps1 -Target Release
